import asyncio, datetime, os, re
from playwright.async_api import async_playwright
# 帳簿のチェック（今日＞経費を登録）。node test/serve_svc.mjs で起動した仮のサーバーで動かす
B='http://127.0.0.1:8787'
SHOTS='shots'
os.makedirs(SHOTS, exist_ok=True)
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch(); a=await b.new_page(viewport={'width':390,'height':844}, device_scale_factor=2); errs=[]
        a.on('pageerror',lambda e:errs.append(str(e)))
        dialogs=[]
        def on_dialog(dg): dialogs.append(dg.message); asyncio.ensure_future(dg.accept())
        a.on('dialog', on_dialog)
        await a.goto(B+'/admin'); await a.wait_for_timeout(600)
        if await a.is_visible('#pw'): await a.fill('#pw','pw-test-123'); await a.click('#loginBtn')
        await a.wait_for_selector('[data-act=rcptOpen]'); await a.click('[data-act=rcptOpen]')
        # Squareの未入力：まず1件だけ → 次からまとめて
        await a.wait_for_selector('[data-key=squn]', timeout=20000); await a.wait_for_timeout(400)
        sq=a.locator('[data-key=squn]')
        print('Squareの未入力:', (await sq.inner_text()).replace('\n',' / ')[:300])
        await sq.screenshot(path=SHOTS+'/squn.png')
        await sq.locator('[data-act=sqEnter]').click(); await a.wait_for_timeout(1800)
        print('1件登録したあと:', await sq.locator('[data-act=sqEnter]').inner_text())
        await sq.locator('[data-act=sqEnter]').click(); await a.wait_for_timeout(2000)
        print('まとめて登録したあと:', (await a.locator('[data-key=squn]').inner_text()).replace('\n',' / ')[:200] if await a.locator('[data-key=squn]').count() else 'カードなし')
        await a.wait_for_selector('[data-key=book] .bk', timeout=20000); await a.wait_for_timeout(500)
        card=a.locator('[data-key=book]')
        print('直すところ:', await card.locator('.bk').count(), '／見出し:', [t.replace('\n',' ') for t in await card.locator('.bk .why').all_inner_texts()])
        print('根拠:', [t for t in await card.locator('.bk .basis').all_inner_texts()][:4])
        print('今日に締めの表はない:', await card.locator('.gcalc').count(), '／会計へのリンク:', (await card.locator('[data-act=goAcct]').inner_text()).replace('\n',' / '))
        # 通帳にない動き：どうしたか選ぶ＋Claudeに相談
        while await card.locator('[data-act=bookMore]').count(): await card.locator('[data-act=bookMore]').click(); await a.wait_for_timeout(200)
        fee=card.locator('.bk', has_text='No.3 il Centrino')
        print('通帳にない入金:', (await fee.inner_text()).replace('\n',' / '))
        print('選べる直し方:', await fee.locator('select option').all_inner_texts())
        await fee.locator('[data-act=bookAsk]').click(); await a.wait_for_timeout(150)
        print('相談中:', await fee.locator('.aithink').count())
        await a.wait_for_selector('[data-key="bk:bk:BK21:6000"] .askans', timeout=10000)
        print('Claudeの答え:', (await fee.locator('.askans').inner_text()).replace('\n',' '), '／選ばれた:', await fee.locator('select').input_value())
        await fee.screenshot(path=SHOTS+'/book_bank.png')
        await fee.locator('[data-act=bookFix]').click(); await a.wait_for_timeout(1500)
        print('直したあと:', await card.locator('.bk', has_text='No.3 il Centrino').count())
        out=card.locator('.bk', has_text='SUBLINE')
        print('通帳にない出金の選び方:', await out.locator('select option').all_inner_texts())
        first=card.locator('.bk', has_text='八百鮮')
        print('科目の提案:', await first.locator('select').input_value())
        await first.locator('[data-act=bookFix]').click(); await a.wait_for_timeout(1500)
        print('直したあと:', await card.locator('.bk', has_text='八百鮮').count())
        await card.locator('.bk', has_text='近鉄').locator('[data-act=bookFix][data-to=現金]').click(); await a.wait_for_timeout(1500)
        print('現金で払った:', await card.locator('.bk', has_text='近鉄').count())
        await card.locator('[data-act=bookAi]').click(); await a.wait_for_timeout(200)
        print('Claudeが見ている:', await card.locator('svg.clawd').count())
        await a.wait_for_selector('[data-key=book] .bk .why svg.spark', timeout=10000)
        print('Claudeの指摘:', (await card.locator('.bk:has(.why svg.spark)').first.inner_text()).replace('\n',' / '))
        await card.screenshot(path=SHOTS+'/book_ai.png')
        # 設定＞会計：締めの確認
        await card.locator('[data-act=goAcct]').click()
        await a.wait_for_selector('[data-key=close] .clbox', timeout=20000); await a.wait_for_timeout(500)
        cl=a.locator('[data-key=close]')
        print('会計のタブ:', await a.locator('[data-act=setPart].on').inner_text(), '／締めの日:', await cl.locator('[data-act=acctDate].on').inner_text())
        print('締め:', (await cl.inner_text()).replace('\n',' / ')[:500])
        await a.fill('#clCash', '30000'); await a.fill('#clBank', '600000'); await cl.locator('[data-act=acctCompare]').click(); await a.wait_for_timeout(1500)
        print('比べた:', (await cl.inner_text()).replace('\n',' / ')[:700])
        print('理由の候補:', [t.replace('\n',' ') for t in await cl.locator('.causes li').all_inner_texts()][:4])
        await cl.screenshot(path=SHOTS+'/acct_close.png')
        await cl.locator('[data-key="cl:bank"]').screenshot(path=SHOTS+'/acct_bank.png')
        print('帳尻合わせ:', await cl.locator('.cashadj').all_inner_texts())
        await cl.locator('[data-act=adjOpen][data-v=cash]').click(); await a.wait_for_timeout(300)
        go=cl.locator('[data-act=adjGo][data-v=cash]')
        print('選ぶ前は押せない:', await go.is_disabled())
        await cl.locator('[data-act=adjHow][data-a=cash][data-v=misc]').click()
        await a.fill('[data-adjamt=cash]', '1,234')
        print('ちがう金額では押せない:', await go.is_disabled())
        amt=re.search(r'¥([\d,]+)', await cl.locator('[data-key="adj:cash"] small').first.inner_text()).group(1)
        await a.fill('[data-adjamt=cash]', amt)
        print('差の金額で押せる:', not await go.is_disabled())
        await cl.locator('[data-key="adj:cash"]').screenshot(path=SHOTS+'/acct_adj.png')
        await go.click(); await a.wait_for_timeout(2000)
        print('合わせたあと:', (await cl.locator('[data-key="cl:cash"]').inner_text()).replace('\n',' / '), '／確認:', dialogs[-1].replace('\n',' '))
        sc=a.locator('[data-key=salescheck]')
        btn=sc.locator('[data-act=acctDays]').first
        if await btn.count():
            await btn.click(); await a.wait_for_timeout(300)
            print('理由を開く:', await sc.locator('.causes').count(), await sc.locator('[data-act=acctDays]').first.inner_text())
            await sc.locator('[data-act=acctDays]').first.click(); await a.wait_for_timeout(300)
            print('閉じる:', await sc.locator('.causes').count())
        print('売上:', (await sc.inner_text()).replace('\n',' / ')[:200])
        nt=a.locator('[data-key=notes]')
        print('気になるところ:', (await nt.inner_text()).replace('\n',' / ')[:300])
        await a.locator('[data-key=salescheck]').screenshot(path=SHOTS+'/acct_sales.png')
        await nt.screenshot(path=SHOTS+'/acct_notes.png')
        print('dialogs', dialogs, 'errors', errs)
        await b.close()
asyncio.run(main())
