import { start } from './env.mjs';
const env=await start({port:8819, linePort:8820});
const B='http://127.0.0.1:8819';
const P=async (p,b,h={})=>{const r=await fetch(B+p,{method:'POST',headers:{'content-type':'application/json',...h},body:JSON.stringify(b||{})});return {status:r.status,body:await r.json(),headers:r.headers}};
const add=(s,n)=>{const d=new Date(s+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const T=new Date(Date.now()+9*3600e3).toISOString().slice(0,10);
let D=add(T,6); while(new Date(D+'T00:00:00Z').getUTCDay()!==6) D=add(D,1);
const a=await P('/admin/api/login',{password:'pw-test-123'});
const AD={cookie:a.headers.get('set-cookie').split(';')[0],'x-epii':'1'};
let st=(await P('/admin/api/boot',{},AD)).body.settings; st.seats=10; st.maxGuests=6; for (const d in st.weekly) st.weekly[d]=['morning','lunch','dinner']; await P('/admin/api/saveSettings',st,AD);
const cs=(await P('/admin/api/courses',{},AD)).body.courses;
const din=cs.find(c=>c.name==='季節の薬膳フレンチ'), omak=cs.find(c=>c.name==='シェフおまかせ');
let r=await P('/admin/api/saveCourse',{...din,cap:4},AD);
console.log('① ディナーコースを同時4名まで:', r.body.courses.find(c=>c.id===din.id).cap);
const fresh=async()=>({authorization:'Bearer '+(await P('/api/login',{idToken:'x'+Math.random().toString(36).slice(2,8)})).body.token});
const mk=(time,g,cid,h)=>P('/api/request',{data:{date:D,time,guests:g,courseId:cid,sei:'テスト',mei:'太郎',phone:'09011112222'}},h);
r=await mk('18:00',2,din.id,await fresh()); console.log('   18:00 ディナー2名:', r.body.ok?'OK':r.body.message);
r=await mk('19:00',2,din.id,await fresh()); console.log('   19:00 ディナー2名（重なって計4名）:', r.body.ok?'OK':r.body.message);
r=await mk('19:30',1,din.id,await fresh()); console.log('   19:30 ディナー1名（5名目）:', r.body.ok?'通ってしまう':r.body.message);
r=await mk('19:30',2,omak.id,await fresh()); console.log('   19:30 おまかせ2名（別メニュー・席は空き）:', r.body.ok?'OK':r.body.message);
const data=(await P('/api/init',{},await fresh())).body.data;
console.log('   予約ページに渡るメニューの上限:', data.courses.find(c=>c.id===din.id).cap, '| 席情報にメニュー:', data.holds.every(h=>'course' in h));
r=await P('/admin/api/addPhone',{date:D,time:'18:30',guests:1,name:'電話',courseId:din.id},AD);
console.log('   電話予約でディナー1名（上限超え）:', r.body.full?'確認が出る':(r.body.ok?'通ってしまう':r.body.message));
// ② 早じまい（ランチだけ）
await P('/admin/api/addBlock',{date:D,type:'stop',start:'12:30',end:st.sessions.lunch.close,memo:'早じまい（ランチ）'},AD);
const lun=cs.find(c=>c.name==='養生ランチ');
r=await mk('13:00',1,lun.id,await fresh()); console.log('② ランチ12:30〜停止 → 13:00ランチ:', r.body.ok?'通ってしまう':'受付停止');
r=await mk('18:30',1,omak.id,await fresh()); console.log('   同じ日のディナー18:30:', r.body.ok?'受け付ける':r.body.message);
await env.stop();
